
networks:
  media_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.26.0.0/16
  vpn_network:
    driver: bridge
    internal: true
  proxy_network:
    driver: bridge

services:
  # ===========================================
  # VPN Gateway - MUST BE STARTED FIRST
  # ===========================================
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - VPN_SERVICE_PROVIDER=${VPN_SERVICE_PROVIDER}
      - VPN_TYPE=${VPN_TYPE}
      - OPENVPN_USER=${OPENVPN_USER}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - TZ=${TZ}
      - HEALTH_VPN_DURATION_INITIAL=30s
      - HEALTH_SUCCESS_WAIT_DURATION=5s
      - FIREWALL_OUTBOUND_SUBNETS=172.26.0.0/16,172.21.0.0/16,172.22.0.0/16
    volumes:
      - ${CONFIG_ROOT}/gluetun:/gluetun
    ports:
      - "8080:8080"  # qBittorrent WebUI
      - "6881:6881"  # qBittorrent incoming connections
      - "6881:6881/udp"
    networks:
      - vpn_network
      - media_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 30s

  # ===========================================
  # REVERSE PROXY & SSL
  # ===========================================
  traefik:
    image: traefik:v3.1
    container_name: traefik
    restart: unless-stopped
    command:
      - --api.dashboard=true
      - --api.debug=false
      - --log.level=${LOG_LEVEL}
      - --providers.docker=true
      - --providers.docker.network=proxy_network
      - --providers.docker.exposedbydefault=false
      - --providers.file.directory=/dynamic
      - --providers.file.watch=true
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --certificatesresolvers.letsencrypt.acme.email=${EMAIL}
      - --certificatesresolvers.letsencrypt.acme.storage=/acme.json
      - --certificatesresolvers.letsencrypt.acme.httpchallenge=true
      - --certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https
    environment:
      - TZ=${TZ}
    ports:
      - "8091:80"
      - "${HTTPS_PORT}:443"
      - "8090:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${CONFIG_ROOT}/traefik/acme.json:/acme.json
      - ${CONFIG_ROOT}/traefik/dynamic:/dynamic:ro
    networks:
      - proxy_network
      - media_network

  # ===========================================
  # AUTHENTICATION & AUTHORIZATION
  # ===========================================
  authelia:
    image: authelia/authelia:latest
    container_name: authelia
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - AUTHELIA_JWT_SECRET=${AUTHELIA_JWT_SECRET}
      - AUTHELIA_SESSION_SECRET=${AUTHELIA_SESSION_SECRET}
      - AUTHELIA_STORAGE_ENCRYPTION_KEY=${AUTHELIA_STORAGE_ENCRYPTION_KEY}
      - AUTHELIA_DEFAULT_2FA_METHOD=${AUTHELIA_DEFAULT_2FA_METHOD}
      - AUTHELIA_LOG_LEVEL=${AUTHELIA_LOG_LEVEL}
    volumes:
      - ${CONFIG_ROOT}/authelia:/config
    ports:
      - "9091:9091"
    networks:
      - proxy_network
      - media_network

  # ===========================================
  # MEDIA SERVER
  # ===========================================
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    user: ${PUID}:${PGID}
    environment:
      - TZ=${TZ}
      - JELLYFIN_PublishedServerUrl=http://localhost:8096
    volumes:
      - ${CONFIG_ROOT}/jellyfin:/config
      - ${DATA_ROOT}/media:/media
      - /tmp/jellyfin-transcode:/transcode
    devices:
      - /dev/dri:/dev/dri  # Intel/AMD GPU
    ports:
      - "8096:8096"
    networks:
      - media_network
      - proxy_network

  # ===========================================
  # REQUEST MANAGEMENT
  # ===========================================
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    restart: unless-stopped
    user: ${PUID}:${PGID}
    environment:
      - LOG_LEVEL=${LOG_LEVEL}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_ROOT}/jellyseerr:/app/config
    ports:
      - "5055:5055"
    networks:
      - media_network
      - proxy_network

  # ===========================================
  # INDEXER MANAGEMENT
  # ===========================================
  prowlarr:
    image: linuxserver/prowlarr:latest
    container_name: prowlarr
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_ROOT}/prowlarr:/config
    ports:
      - "9696:9696"
    networks:
      - media_network
      - proxy_network

  # ===========================================
  # LIBRARY MANAGERS (*ARR SUITE)
  # ===========================================
  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_ROOT}/radarr:/config
      - ${DATA_ROOT}/media/movies:/movies
      - ${DATA_ROOT}/torrents:/downloads
    ports:
      - "7878:7878"
    networks:
      - media_network
      - proxy_network

  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_ROOT}/sonarr:/config
      - ${DATA_ROOT}/media/tv:/tv
      - ${DATA_ROOT}/torrents:/downloads
    ports:
      - "8989:8989"
    networks:
      - media_network
      - proxy_network

  lidarr:
    image: linuxserver/lidarr:latest
    container_name: lidarr
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_ROOT}/lidarr:/config
      - ${DATA_ROOT}/media/music:/music
      - ${DATA_ROOT}/torrents:/downloads
    ports:
      - "8686:8686"
    networks:
      - media_network
      - proxy_network

  # ===========================================
  # SUBTITLE MANAGER
  # ===========================================
  bazarr:
    image: linuxserver/bazarr:latest
    container_name: bazarr
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_ROOT}/bazarr:/config
      - ${DATA_ROOT}/media/movies:/movies
      - ${DATA_ROOT}/media/tv:/tv
    ports:
      - "6767:6767"
    networks:
      - media_network
      - proxy_network

  # ===========================================
  # DOWNLOAD CLIENT
  # ===========================================
  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_PORT=8080
    volumes:
      - ${CONFIG_ROOT}/qbittorrent:/config
      - ${DATA_ROOT}/torrents:/downloads
    ports:
      - "8080:8080"
      - "6881:6881"
      - "6881:6881/udp"
    networks:
      - media_network
      - proxy_network

  # ===========================================
  # CLOUDFLARE BYPASS
  # ===========================================
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    restart: unless-stopped
    environment:
      - LOG_LEVEL=${LOG_LEVEL}
      - TZ=${TZ}
    ports:
      - "8191:8191"
    networks:
      - media_network

  # ===========================================
  # EXTRACTION TOOL
  # ===========================================
  unpackerr:
    image: golift/unpackerr:latest
    container_name: unpackerr
    restart: unless-stopped
    user: ${PUID}:${PGID}
    environment:
      - TZ=${TZ}
      # Sonarr Configuration
      - UN_SONARR_0_URL=http://sonarr:${SONARR_PORT}
      - UN_SONARR_0_API_KEY=
      - UN_SONARR_0_PATHS_0=/downloads/tv
      # Radarr Configuration  
      - UN_RADARR_0_URL=http://radarr:${RADARR_PORT}
      - UN_RADARR_0_API_KEY=
      - UN_RADARR_0_PATHS_0=/downloads/movies
      # Lidarr Configuration
      - UN_LIDARR_0_URL=http://lidarr:${LIDARR_PORT}
      - UN_LIDARR_0_API_KEY=
      - UN_LIDARR_0_PATHS_0=/downloads/music
      # Readarr Configuration (Disabled - service not available)
      # - UN_READARR_0_URL=http://readarr:${READARR_PORT}
      # - UN_READARR_0_API_KEY=
      # - UN_READARR_0_PATHS_0=/downloads/books
    volumes:
      - ${DATA_ROOT}/torrents:/downloads
    networks:
      - media_network

  # ===========================================
  # DASHBOARD
  # ===========================================
  heimdall:
    image: linuxserver/heimdall:latest
    container_name: heimdall
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_ROOT}/heimdall:/config
    ports:
      - "8082:80"
    networks:
      - proxy_network
      - media_network
